#ifndef MANGO_2D_CONST_H_
#define MANGO_2D_CONST_H_
const int DEFAULT_WALL_WIDTH = 12;
const int DEFAULT_SINGLE_DOOR_LENGTH = 100;
const int DEFAULT_DOOR_HEIGHT = 180;
const int DEFAULT_WINDOW_HEIGHT = 80;
const int DEFAULT_WINDOW_Z = 80;
#endif